### ISSUE TITLE
How to generate demo_dock.csv

### ISSUE THREAD

**Issue by nwod-edispu** [tencent-ailab/Interformer#2]
How can i generate demo_dock.csv for unknown protein-ligand pairs?

**Comment by lkfo415579** [comment]
You can easily create a demo_dock.csv file by defining the protein and ligand prefixes in the "Target" column and the ligand names of SDF in the "Molecule ID" column (other columns are useless during inference). There's a helpful script, [inter_sdf2csv.py](https://github.com/tencent-ailab/Interformer/blob/master/tools/inference/inter_sdf2csv.py), which generates this CSV file using a prepared .sdf file.

**Comment by wenchangzhou-qtx** [comment]
@lkfo415579 , can you provide example inputs and how to run it? Seems there are certain fields need to be present in the SDF file. Thanks!

**Comment by lkfo415579** [comment]
> @lkfo415579 , can you provide example inputs and how to run it? Seems there are certain fields need to be present in the SDF file. Thanks!

You can find the example files in the `examples/` folder. Follow the instructions from `README.md` to do it yourself once, and you will understand how to modify the input file for your own use.

By default, the molecule in the SDF file is located as the first molecule or using the column **pose_rank**. Alternatively, you can use the parameter `--use_mid` to locate the molecule in the SDF file. Just ensure that the name of the molecule in the SDF file matches the **Molecule ID** in the input CSV file.

**Comment by wensm77** [comment]
> You can easily create a demo_dock.csv file by defining the protein and ligand prefixes in the "Target" column and the ligand names of SDF in the "Molecule ID" column (other columns are useless during inference). There's a helpful script, [inter_sdf2csv.py](https://github.com/tencent-ailab/Interformer/blob/master/tools/inference/inter_sdf2csv.py), which generates this CSV file using a prepared .sdf file.通过在 “Target” 列中定义蛋白质和配体前缀，在 “Molecule ID” 列中定义 SDF 的配体名称，您可以轻松创建 demo_dock.csv 文件（其他列在推理过程中无用）。有一个有用的脚本 [inter_sdf2csv.py](https://github.com/tencent-ailab/Interformer/blob/master/tools/inference/inter_sdf2csv.py)，它使用准备好的 .sdf 文件生成此 CSV 文件。

Which .sdf file? I followed the readme file and got the following results:
![image](https://github.com/user-attachments/assets/96a913a8-57ec-4e18-a553-0e30e2dff25d)
Getting an error when sampling the energy model
```
test,@ [Bindingdata] Valid Samples:0 / 1
Traceback (most recent call last):
  File "/home/wensm/Interformer/inference.py", line 119, in <module>
    bind_data = BindingData(args, n_jobs=1 if args['debug'] else args['n_jobs'], istrain=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wensm/Interformer/interformer/data/dataset/bindingdata.py", line 101, in __init__
    data = self._pre_complex(df, cache_path, n_jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wensm/Interformer/interformer/data/dataset/bindingdata.py", line 264, in _pre_complex
    self._write_dataset(data, df, cache_path)
  File "/home/wensm/Interformer/interformer/data/dataset/common_dataset.py", line 11, in _write_dataset
    LmdbPPI.make_shared(data, cached_path)
  File "/home/wensm/Interformer/interformer/data/data_stucture/lmdb_dataset.py", line 108, in make_shared
    LmdbPPI.stats_data(data)
  File "/home/wensm/Interformer/interformer/data/data_stucture/lmdb_dataset.py", line 102, in stats_data
    f", ligand_len{get_max_mean_min(ligand_lens)}"
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wensm/Interformer/interformer/data/data_stucture/lmdb_dataset.py", line 98, in get_max_mean_min
    return f":max={max(x)},mean={np.mean(x):4f},median={np.median(x):4f},std={np.std(x):4f},min={np.min(x)}"
                   ^^^^^^
ValueError: max() iterable argument is empty
```
my demo_dock.csv is as follow:
```
Target,Molecule ID
test,910
```
And the ligand number in the initial pdb file is 910
```
HETATM 2188  C_1 910 B   1      -5.184  -2.197   4.346  1.00 58.15           C  
HETATM 2189  O_1 910 B   1      -6.427  -2.473   3.718  1.00 67.54           O  
HETATM 2190  C_2 910 B   1      -7.463  -1.664   3.952  1.00 79.50           C  
HETATM 2191  O_2 910 B   1      -7.343  -0.652   4.569  1.00 67.62           O  
HETATM 2192  C_3 910 B   1      -8.819  -2.140   3.439  1.00 80.64           C  
HETATM 2193  N_1 910 B   1      -9.659  -2.425   4.583  1.00 76.06           N  
...
```

**Comment by lkfo415579** [comment]
@wensm77 

The ligand folder should contain a reference ligand in SDF format, positioned inside the binding pocket. (ligand/test_ligand.sdf)

Additionally, the protein pocket PDB file should not include the reference ligand. (pocket/test_pocket.pdb)

The program will use the reference ligand to automatically intercept the binding pocket. Could you please upload these files here so I can review them?

**Comment by wensm77** [comment]
sure!thank for your reply soon!
GitHub cannot upload .pdb file and .sf file, so i change suffix to .log
[test_pocket.log](https://github.com/user-attachments/files/18090574/test_pocket.log)

[test_docked.log](https://github.com/user-attachments/files/18090573/test_docked.log)

**Comment by lkfo415579** [comment]
@wensm77 The `test_docked.sdf` should be the reference ligand from PDB. (crystal ligand) And please remove the reference ligand from the PDB file.

**Comment by wensm77** [comment]
@lkfo415579 
Hi!
So I just need a pdb file containing only amino acids, and a .sdf file of ligand and then repeat the steps in the readme?
Actually, I used chai1 to infer a protein-small molecule structure and wanted to use the interformer for checking.

And now, i found the bug in my test.
I have to change all these code in interformer and then it can run
```
# sanitize=False
Chem.SDMolSupplier(sdf_f, sanitize=False, removeHs=True)
```
In jupyter, it report an error
```
[16:32:22] Explicit valence for atom # 10 O, 3, is greater than permitted
[16:32:22] ERROR: Could not sanitize molecule ending on line 90
[16:32:22] ERROR: Explicit valence for atom # 10 O, 3, is greater than permitted
```
I am not good at bioinformatics, why do I get this error?

**Comment by lkfo415579** [comment]
@wensm77 The molecule in the SDF file is incorrect, so you should verify its covalent bonds. Instead of taking the molecule from the PDB file, download the SDF file directly from the RCSB website, as the PDB file may lose crucial information about the covalent bonds.

**Comment by nwod-edispu** [comment]
I  generated the CSV file using ```inter_sdf2csv.py```, which outputs the following columns: ```[Target, pose_rank, uff_pose_rank, Molecule ID]```. Then everything works as expected.
However, when I run the following command:
```python docking/merge_summary_input.py $DOCK_FOLDER/ligand_reconstructing/stat_concated.csv examples/demo_dock.csv```
I encounter the following exception:
```KeyError: 'pose_rank', from ' merge_summary_input.py", line 16```.
It seems that the ```$DOCK_FOLDER/ligand_reconstructing/stat_concated.csv``` file contains a column named ```pose_rank```. After merging, I end up with two columns: ```["pose_rank_x", "pose_rank_y"]```, and the original key ```pose_rank``` is no longer present, which causes the KeyError.

**Comment by lkfo415579** [comment]
@nwod-edispu Yes, thank you for pointing out the bug here. The `merge_summary_input.py` should only use the pose_rank value from `stat_concated.csv`. Bug is fixed.
