### ISSUE TITLE
Apply Interformer to ligand molecules in SMILES format.

### ISSUE THREAD

**Issue by liyue9129** [tencent-ailab/Interformer#4]
Hi!
Great work!

I have a collection of ligand molecules in SMILES format and crystal protein 10Å pockets. How should I apply Interformer in this scenario? Is it sufficient to simply use obabel to convert the ligand molecules from SMILES format to SDF format, and then follow the steps outlined in the README for [the Inference of Docking Pipeline and PoseScore/Affinity Pipeline](https://github.com/tencent-ailab/Interformer?tab=readme-ov-file#inference-of-docking-pipeline-and-posescoreaffinity-pipeline)? Are there any other modifications or steps that need to be considered?

Thank you !
Best wishes!

**Comment by lkfo415579** [comment]
The best way to prepare ligands and proteins is by using Schrödinger's Protein Wizard and LigPrep. This well-known professional pharmaceutical software excels at preparing protein and ligand structures. It's important to handle many details carefully, as they can significantly affect the results. If you don't have access to this software, you can follow my steps instead, and it should work fine.

**Comment by liyue9129** [comment]
Thank for your help！

I attempted to apply Interformer to virtual screening (a single protein and many ligand molecules). However, I encountered some issues when calculating the energy function using unbound ligand conformations. （Specifically, I used the parameter --uff_as_ligand and made minor modifications to [bindingdata.py](https://github.com/tencent-ailab/Interformer/blob/master/interformer/data/dataset/bindingdata.py#L186) to ensure that all ligands used for calculating features（[here](https://github.com/tencent-ailab/Interformer/blob/master/interformer/feats/gnina_types/gnina_featurizer.py#L1096)） were in their unbound conformations.） As a result, I successfully obtained five energy functions (I used five samples for debugging). Is it correct to calculate the energy function this way?
![image](https://github.com/user-attachments/assets/7e99d1b8-5ae2-4cae-b56e-c825513bc29f)

However, problems arose during the Monte Carlo sampling phase due to the deeply nested paths. Would it be possible for you to share the code you used for virtual screening? That would be a tremendous help！

Additionally, I would like to ask whether the input protein and ligand must be in their bound conformations (or docked ligand conformations)？For each protein-ligand pair, a single energy function is obtained to guide subsequent Monte Carlo searches for ligand binding conformations？

Thank you！
Best wishes！

**Comment by lkfo415579** [comment]
@liyue9129 

I upload a new example demonstrate how to dock multiple ligands with one protein. Please refer to [vs](https://github.com/tencent-ailab/Interformer/tree/master/applications/virtual_screening).

>Additionally, I would like to ask whether the input protein and ligand must be in their bound conformations (or docked ligand conformations)？For each protein-ligand pair, a single energy function is obtained to guide subsequent Monte Carlo searches for ligand binding conformations？

Yes. the ligand/$PDB_docked.sdf should be in the binding site, you may use a docking ligand conformation as alternative. (this file is only for locating binding site)

>For each protein-ligand pair, a single energy function is obtained to guide subsequent Monte Carlo searches for ligand binding conformations？

Yes, you are correct.

**Comment by liyue9129** [comment]
Thank you so much! The issue has been resolved！
